[project]
name = "letterboxed-absa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dilharajay", email = "dilhara5287@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.0",
    "dagster>=1.13.21",
    "emoji>=2.15.0",
    "fastapi>=0.141.1",
    "ftfy>=6.3.1",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.9",
    "matplotlib>=3.11.1",
    "openai>=3.5.0",
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "pyarrow>=25.0.1",
    "seaborn>=0.13.2",
    "spacy>=3.8.16",
    "tqdm>=4.70.0",
    "wikipedia>=1.4.0",
]

[project.scripts]
letterboxed-absa = "letterboxed_absa:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
